### PR TITLE
Mass consolidation and refactor of Photo journey

### PR DESCRIPTION
**Pull request by rodericktan**
- Add OIX photo journey back in
- Consolidate all photo journeys into single `photo` directory
- Remove redundant code, pages and directories
- Mass rename of photo journey
- Mass refactor of markup to use templates, routes, form wizard, etc
- Mass fix of broken paths and routes, buggy markup and styling, etc

### CODE REVIEW

**Comment by hvekriya** [comment]
@rodericktan if you do FTA journey there is no back button on `photo/digital-photo` Can we add javascript history back on that?

**Comment by hvekriya** [comment]
`/prototype/photo/final-checks` the radio button "I want to get a different photo" doesn't work. It is meant to take you back to upload page.

**Comment by rodericktan** [comment]
> @rodericktan if you do FTA journey there is no back button on `photo/digital-photo` Can we add javascript history back on that?

Added temporary backlink in. Works in 1 direction only.

> `/prototype/photo/final-checks` the radio button "I want to get a different photo" doesn't work. It is meant to take you back to upload page.

Taking user back to `choose-photo-method` page is reflective of production.

**Comment by hvekriya** [comment]
> > @rodericktan if you do FTA journey there is no back button on `photo/digital-photo` Can we add javascript history back on that?
> 
> Added temporary backlink in. Works in 1 direction only.
> 
> > `/prototype/photo/final-checks` the radio button "I want to get a different photo" doesn't work. It is meant to take you back to upload page.
> 
> Taking user back to `choose-photo-method` page is reflective of production.

It doesn't take you back at all is what I meant. It just does what the other radio does

**Comment by rodericktan** [comment]
> > > @rodericktan if you do FTA journey there is no back button on `photo/digital-photo` Can we add javascript history back on that?
> > 
> > 
> > Added temporary backlink in. Works in 1 direction only.
> > > `/prototype/photo/final-checks` the radio button "I want to get a different photo" doesn't work. It is meant to take you back to upload page.
> > 
> > 
> > Taking user back to `choose-photo-method` page is reflective of production.
> 
> It doesn't take you back at all is what I meant. It just does what the other radio does

Strange, it was working before. Fixed.

**Pull request merged**
